# Local postgres database for testing
services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5

  backup-test:
    image: ghcr.io/mmoreiradj/back2back-postgres-backup:latest
    build:
      context: .
      dockerfile: pgbackup.Dockerfile
    environment:
      PGDUMP_DIR: /tmp
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: postgresql
      PGPORT: 5432
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: pgbackup
      AWS_ACCESS_KEY_ID: accesskey
      AWS_SECRET_ACCESS_KEY: secretkey
      AWS_DEFAULT_REGION: ''

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    ports:
    - 9000:9000
    - 9001:9001
    volumes:
    - minio-data:/data

volumes:
  postgres-data:
  minio-data:
